[0.000000] (-) TimerEvent: {}
[0.000699] (NIDS_PKG) JobQueued: {'identifier': 'NIDS_PKG', 'dependencies': OrderedDict()}
[0.000764] (NIDS_PKG) JobStarted: {'identifier': 'NIDS_PKG'}
[0.099864] (-) TimerEvent: {}
[0.200217] (-) TimerEvent: {}
[0.300522] (-) TimerEvent: {}
[0.400878] (-) TimerEvent: {}
[0.501171] (-) TimerEvent: {}
[0.542665] (NIDS_PKG) StderrLine: {'line': b'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_parallel_executor/executor/parallel.py", line 67, in execute\n    loop.run_until_complete(future)\n  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete\n    self.run_forever()\n  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever\n    self._run_once()\n  File "/usr/lib/python3.8/asyncio/base_events.py", line 1823, in _run_once\n    event_list = self._selector.select(timeout)\n  File "/usr/lib/python3.8/selectors.py", line 468, in select\n    fd_event_list = self._selector.poll(timeout, max_ev)\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__\n    rc = await self.task(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__\n    return await task_method(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_python/build.py", line 105, in build\n    return await extension.build(additional_hooks=additional_hooks)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 81, in build\n    available_commands = await self._get_available_commands(\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 171, in _get_available_commands\n    output = await check_output(\n  File "/usr/lib/python3/dist-packages/colcon_core/subprocess.py", line 128, in check_output\n    assert not rc, f\'Expected {args} to pass: {stderr_data}\'\nAssertionError: Expected [\'/usr/bin/python3\', \'setup.py\', \'--help-commands\'] to pass: Traceback (most recent call last):\n  File "setup.py", line 1, in <module>\n    from setuptools import setup\n  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 19, in <module>\n    from setuptools.dist import Distribution, Feature\n  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 36, in <module>\n    from setuptools import windows_support\n  File "/usr/lib/python3/dist-packages/setuptools/windows_support.py", line 2, in <module>\n    import ctypes\n  File "/usr/lib/python3.8/ctypes/__init__.py", line 170, in <module>\n    class c_long(_SimpleCData):\nKeyboardInterrupt\n\n'}
[0.543199] (NIDS_PKG) JobEnded: {'identifier': 'NIDS_PKG', 'rc': 'SIGINT'}
[0.553048] (-) EventReactorShutdown: {}
